version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        container_name: my_web
        volumes:
            - ./www:/var/www
        ports:
            - "8000:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        container_name: my_app
        volumes:
            - ./www:/var/www
        links:
            - mysql:hoge
    mysql:
        restart: always
        image: mysql:5 # 8系だと認証方式が変更されているので注意
        container_name: my_db
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=laraveltest"
        ports:
            - "33060:33060"
