version: '3'
services:
    web:
        build: ./web
        ports:
            - "9000:80"
        depends_on:
            - app
    app:
        build: ./app
        env_file: .env
        volumes:
            - ./app/src:/var/www/laravel
        depends_on:
            - db
            - redis
    db:
        restart: always
        image: mysql:5 # 8系だと認証方式が変更されているので注意
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=laraveltest"
        ports:
            - "9306:3306"
    redis:
        restart: always
        image: redis:latest
        volumes:
            - ./redis:/data
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
